map $http_user_agent $ver {
    "~^.*(EEA|EES|EFSW|EMSX|ESFW)+\s+Update.*BPC\s+(\d+)\..*$" "ep$2";
    "~^.*Update.*BPC\s+(\d+)\..*$" "v$1";
    default "ep13";
}

server {
    listen 7860 default_server;
    server_name _;

    root /app/mirror;
    index index.html;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive" always;

    location = /health {
        default_type text/plain;
        return 200 "OK\n";
    }

    location = /sync {
        proxy_pass http://127.0.0.1:9999;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Cache-Control "no-store";
    }

    location = /synclog {
        default_type text/plain;
        charset utf-8;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
        alias /app/mirror/sync.log;
    }

    location ~* \.(log|txt)$ {
        default_type text/plain;
        charset utf-8;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
    }

    location ~* \.ver$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";

        if ($ver ~ "^ep[6-9]$") { rewrite ^/(dll/)?update.ver$ /eset_upd/$ver/$1update.ver break; }
        if ($ver ~ "^ep1[0-9]$") { rewrite ^/(dll/)?update.ver$ /eset_upd/$ver/$1update.ver break; }
        if ($ver ~ "^v[3-8]$") { rewrite ^(.*) /eset_upd/v3/dll/update.ver break; }
        if ($ver ~ "^v1[0-1]$") { rewrite ^(.*) /eset_upd/v10/dll/update.ver break; }
        if ($ver ~ "^v1[2-9]$") { rewrite ^(.*) /eset_upd/$ver/dll/update.ver break; }

        try_files /eset_upd/$ver/dll/update.ver =404;
    }

    location / {
        set $ver_path $ver;
        if ($ver ~ "^v[3-8]$") { set $ver_path v3; }
        if ($ver ~ "^v1[0-1]$") { set $ver_path v10; }

        try_files /data/$ver_path$uri /data/$ver_path/$uri =404;
    }
}
